---

- name: Updating apt cache and installing dependencies
  block:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      register: _pre_update_apt_cache
      until: _pre_update_apt_cache is succeeded
      when:
        - ansible_pkg_mgr == "apt"

    - name: Install dependencies
      ansible.builtin.package:
        name: "{{ grafana_dependencies }}"
        state: present
      register: _install_dep_packages
      until: _install_dep_packages is succeeded
      retries: 5
      delay: 2

- name: Remove conflicting grafana packages
  ansible.builtin.package:
    name: grafana-data
    state: absent
  register: _old_grafana_pkgs

- name: Clean apt cache
  ansible.builtin.command: apt clean
  when:
    - _old_grafana_pkgs is changed
    - ansible_pkg_mgr == "apt"

- name: Add Grafana repository file [RHEL/CentOS]
  ansible.builtin.template:
    src: "{{ grafana_yum_repo_template }}"
    dest: "/etc/yum.repos.d/{{ grafana_yum_repo_template | basename | regex_replace('\\.j2$', '') }}"
    force: true
    backup: true
  when:
    - ansible_pkg_mgr in ['yum', 'dnf']
    - grafana_manage_repo

- name: Adding grafana's apt repo to our sources.list
  when:
    - ansible_pkg_mgr == "apt"
    - grafana_manage_repo
  environment: "{{ grafana_environment }}"
  block:
    - name: Import Grafana GPG signing key [Debian/Ubuntu]
      ansible.builtin.get_url:
        url: "https://apt.grafana.com/gpg.key"
        dest: /usr/share/keyrings/grafana.gpg.asc
        checksum: "{{ grafana_apt_key_checksum }}"
      register: _add_apt_key
      until: _add_apt_key is succeeded
      retries: 5
      delay: 2

    - name: Add Grafana repository [Debian/Ubuntu]
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/grafana.gpg.asc] https://apt.grafana.com stable main
        state: present
        update_cache: true
      register: _update_apt_cache
      until: _update_apt_cache is succeeded
      retries: 5
      delay: 2

- name: Install Grafana
  ansible.builtin.package:
    name: "{{ grafana_package }}"
    state: "{{ (grafana_version == 'latest') | ternary('latest', 'present') }}"
  register: _install_packages
  until: _install_packages is succeeded
  retries: 5
  delay: 2
  notify: restart grafana
